### ISSUE TITLE
[Thumbnail] IMG's alt text is displayed in title when image can't be loaded

### ISSUE THREAD

**Issue by yzqzss** [marienfressinaud/FreshRSS#4078]
**Describe the bug**
[Thumbnail] Alt text is displayed in title when image can't be loaded.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/30341059/147086625-c8344962-ccd2-469b-81ee-bc1c5565c207.png)

**Environment information (please complete the following information):**
- Installation type: Edge Version

**Comment by Alkarex** [comment]
Could you please provide an example of feed illustrating this problem?

**Comment by yzqzss** [comment]
> Could you please provide an example of feed illustrating this problem?

Feed[1]: https://www.blueskyxn.com/feed/
View[1]: https://box.othing.xyz/i/?get=f_707
Feed[2]: https://editor.leonh.space/atom.xml
View[2]: https://box.othing.xyz/i/?get=f_929
Feed[3]: https://chegva.com/feed/
View[3]: https://box.othing.xyz/i/?get=f_414

**Comment by Frenzie** [comment]
> [Thumbnail] Alt text is displayed in title when image can't be loaded.

I'm not sure I follow. That sounds like exactly what's supposed to happen?

**Comment by yzqzss** [comment]
> I'm not sure I follow. That sounds like exactly what's supposed to happen?

But it is mixed with the title to make the title unclear.

**Comment by Frenzie** [comment]
Oh right, I see now. :-) If it's too long it'll overlap.

Since it is a thumbnail that goes together with a title, maybe the alt text could or should just be empty?

**Comment by math-GH** [comment]
I see this issues:

1. the alt text overflows the image box
2. the alt text overlows the article title and makes the title unreadable
3. the alt text is not a good alt text, because it does not describe the picture. It is just the article title

To (3): It should be improved. An empty alt text would be a bad solution (f.e. screen reader would not mention this image (see https://accessibleweb.com/question-answer/when-should-i-use-a-null-or-empty-alt-tag/). I would prefer: alt="Thumbnail" or "Thumbnail to the article" (very generic) or "Thumbnail to: article-title" (my choice). But it will not solve (1) and (2)

The PR could solve (1) and (2).

(3) needs a little discussion here

**Comment by Frenzie** [comment]
It's a purely ornamental image. I didn't realize it was repeating the title, otherwise I surely wouldn't have said maybe above! Put another way, try a screenreader on it and see how long it takes before you tire of hearing the word thumbnail uselessly inserted. ;-) (Graphically while disabling images works well enough to prove the point too.)

I thought it was obtaining the alt text from some attribute or element in the feed saying this is the alt text of the thumbnail, in which case a bad alt text is annoying but technically the feed's fault. That's why I said maybe.

**Comment by Hukuma1** [comment]
<img width="711" alt="freshrsstech" src="https://user-images.githubusercontent.com/54511555/147856675-270d61dd-5a94-4432-9eb5-e6a07bec6ac0.png">

Any ideas on why some feeds don't show the thumbnail?

Feed: https://feeds.feedburner.com/VideoCardzcom
Website: https://videocardz.com/

Edit: Apologies in advance if I should open a new issue instead?

**Comment by math-GH** [comment]
> Edit: Apologies in advance if I should open a new issue instead?

I created a new issue
