### ISSUE TITLE
[BUG] State filter kept since 1.19

### ISSUE THREAD

**Issue by aurmil** [marienfressinaud/FreshRSS#4124]
**Describe the bug**
After 1.19 update, the state filter parameter is kept in URL

**To Reproduce**

1. go to main feed (not displaying already read items, no state param in URL)
2. go to favorites (displaying already read items, state=3 in URL)
3. go to main feed again (already read items are displayed, state=3 in URLà

**Expected behavior**
selected state should match configuration, already read items not displayed, as it was before update, as expected

**Screenshots**
no need

**Environment information (please complete the following information):**
- Device: PC
- OS: Win 10
- Browser: FF 95
- FreshRSS version: 1.19.1
- Database version: SQLite
- PHP version: 7.3
- Installation type: shared hosting

**Additional context**
.

**Comment by Alkarex** [comment]
The issue is only after navigating to favourites / labels, right? https://github.com/FreshRSS/FreshRSS/pull/3986#issuecomment-978941494

**Comment by Alkarex** [comment]
@math-GH Please have a look if you can. The first step is to clarify what the logic should be when interacting with favourites / labels. We might need a distinction between automatic and manual filters

**Comment by aurmil** [comment]
> The issue is only after navigating to favourites / labels, right? [#3986 (comment)](https://github.com/FreshRSS/FreshRSS/pull/3986#issuecomment-978941494)

yes indeed

**Comment by math-GH** [comment]
So it works as designed?
How can I help?

**Comment by Alkarex** [comment]
There is a design problem when being in a view A, navigating to favourites / labels, navigating to view B.
The filters in view A and in view B might be different, just because the user has navigated to favourites / label, which is wrong.
First, we need to re-think what the logic should be (at worst, revert https://github.com/FreshRSS/FreshRSS/pull/3986 )

**Comment by math-GH** [comment]
Let me think loud:

The left aside bar in the normal view/reader view contents the main stream, categories and labels and favorites.

New feed articles are visible in the main stream and categories after polling the feeds.

Favorites and labels are articles after a manual process. I would call it something like "Archive", "Library" or "Read-it-later storage", independent of the categories or main stream.
In "Favorite" the filter for "show favorites" and "Show non-favorites" is useless/senseless (It does not make sense to list articles here, that are NOT a favorite. Toggeling "Show favorites" also does not make sense, because in "Favorites" the user wants to see favorites).

The labels section depends on how the user uses the system. To toggle between read/unread mostly does not make sense, because the user needs to read the article to set the labels.

The main issue is, that "favorites" and "my labels" look equal to "main stream" and the categories.
But both are just a filter on all articles. I repeat: "On ALL articles". But we do not have a "All articles" list. The main stream does not contains all feeds/articles, just the "main" set.

First ideas:
- implementing an "All feeds stream"
- subpages of "All" contains the labels
- subpage of "All" is also the "favorites" list. It has disabled the favorite/non-favorite filter and shows always the favorites. Also disable the read/unread filter and shows always read+unread articles. Or just remove the "favorites" subpage and use the "favorite" filter

I know, that this thoughts are not complete but shows the tricky issues. If you do not understand everything: it does not matter. Just some random thoughts of my brain ;)

My ideas for quick wins:
- a new config option, that enables/disables #3986
- We should (visible) separate "Favorites" and "My labels" from the other streams/categories.
- disable some filter buttons in favorites/my labels to make clear that it is not the common filter

**Comment by Alkarex** [comment]
Related previous PRs:
* https://github.com/FreshRSS/FreshRSS/pull/2766
* https://github.com/FreshRSS/FreshRSS/pull/3472
* https://github.com/FreshRSS/FreshRSS/pull/3986

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/4178
Tests welcome
