### ISSUE TITLE
[BUG] GUI issue in mobile view

### ISSUE THREAD

**Issue by triatic** [marienfressinaud/FreshRSS#4127]
In mobile view, the "Bookmark current query" option is chopped off on the "User queries" dropdown. Tested on Chrome/Android on FreshRSS 1.19.2-dev.

![image](https://user-images.githubusercontent.com/42704418/148386433-37e5bea6-dceb-43f1-bf3f-e1769b18bd98.png)

**Comment by triatic** [comment]
For reference, the "Mark as read" dropdown also drops to the bottom but no fields are chopped off.

**Comment by Alkarex** [comment]
Maybe @math-GH could have a fix idea

**Comment by math-GH** [comment]
@triatic : What is your expectation, when the user clicks on the arrow to open the menu in mobile view?

**Comment by triatic** [comment]
@math-GH at a minimum, "Bookmark current query" should be visible. But I also think the menu should appear closer to the drop-down arrow.

**Comment by math-GH** [comment]
OK, I see.
Here we have 2 different issues

1. the link "Bookmark current query" is not displayed in the mobile view (also the cog icon to navigate to the configuration of the queries). I guess that could be the reason: previous V1.19.0 the config menu was hidden. Since V1.19.0 the config menu is visible. So there should be no reason anymore to hide the user query links. Will fix it with a bug fix for 1.19.2
2. the opened menu is stick to the bottom in mobile view. It is not new in V.19.0. The dropdown menu is not trivial in mobile view. Let me think and create an idea as POC (proof of concept). Will not fix it for 1.19.2. Target: 1.20.0

**Comment by triatic** [comment]
Thanks @math-GH, I look forward to the outcome. I can confirm "Bookmark current query" is now visible.

**Comment by math-GH** [comment]
@triatic If you like you could check the PR #4141

**Comment by triatic** [comment]
@math-GH much better. I like also that the menu is full-width, meaning it is easily able to be tapped by right and left handed users.
