### ISSUE TITLE
Automatically Create and Label Article According to Tags

### ISSUE THREAD

**Issue by Armageddon0x00** [marienfressinaud/FreshRSS#6828]
**Describe the solution you’d like**
I want to automatically label articles according tags included by the feeds article. (If feed includes any tags)

**Describe alternatives you’ve considered**
I have considered creating valid labels and using regex but that did not felt right.

**Additional context**
For example I want these tags to be auto labeled into same article (labels should be created if not exists.)
![image](https://github.com/user-attachments/assets/484482a3-d12f-4814-a04e-94c746ae9187)

Note: I am aware I can filter using tags like this. I need them as labels for future proofing.
![image](https://github.com/user-attachments/assets/f96b2f16-19b3-4730-bcf5-5bcfd03da6ee)

Thanks for your time.

**Comment by Alkarex** [comment]
Hello,
I am not sure of your use-case, but here are a few points already:
The label auto-creation does not exist at the moment, but it is already possible to automatically label articles based on their tags.
Furthermore, it is also possible to save a user-query for a given tag without having to use labels (if your intention is for instance to re-share articles).
Otherwise, auto-creating labels seems like a job for a FreshRSS extension.

**Comment by Armageddon0x00** [comment]
Yeah you are right. I should check if a simple extension can be written for my use case. This felt so much off topic after reading again.
Thanks!

**Comment by Alkarex** [comment]
Update:
* Users labels can be added automatically based on articles tags
* AI classification implemented in https://github.com/FreshRSS/Extensions/pull/458
